[package]
name = "dali-cli"
version = "0.1.0"
authors = ["Austin Jones <austinbaysjones@gmail.com>"]
edition = "2018"

[dependencies]
dali = { path = "../lib/" }

clap = "2.33.0"
uuid = { version = "0.7.4", features = ["v4"] }
